---
  baseURL : "https://snipem.github.io"
  title : "My Projects"
  # logo : "docs/monako/profile.png"

  disableCommitInfo: false

  whitelist:
    - ".md"
    - ".jpg"
    - ".jpeg"
    - ".svg"
    - ".gif"
    - ".png"

  origins:

  - src: https://github.com/snipem/monako-test
    branch: master
    docdir: .
    targetdir: docs/monako

  - src: https://github.com/snipem/commute-tube
    branch: master
    docdir: .
    targetdir: docs/commute

  - src: https://github.com/snipem/psnprices
    branch: master
    docdir: .
    targetdir: docs/psnprices

  - src: https://github.com/snipem/maniacforum.git
    branch: master
    docdir: .
    targetdir: docs/maniacforum

