---
  baseURL : "https://snipem.github.io"
  title : "My Projects"
  logo : "docs/monako/assets/logo/profile.png"

  disableCommitInfo: false

  whitelist:
    - ".md"
    - ".jpg"
    - ".jpeg"
    - ".svg"
    - ".gif"
    - ".png"

  origins:

  - src: https://github.com/snipem/monako
    branch: master
    docdir: .
    targetdir: docs/monako
    whitelist:
      - "README.md"
      - ".png"

  - src: https://github.com/snipem/commute-tube
    branch: master
    docdir: .
    targetdir: docs/commute

  - src: https://github.com/snipem/psnprices
    branch: master
    docdir: .
    targetdir: docs/psnprices

  - src: https://github.com/snipem/maniacforum.git
    branch: master
    docdir: .
    targetdir: docs/maniacforum

# Alfred Workflows

  - src: https://github.com/snipem/alfred-fandom
    branch: master
    docdir: .
    targetdir: docs/alfred-fandom

  - src: https://github.com/snipem/alfred-spotify
    branch: master
    docdir: .
    targetdir: docs/alfred-spotify

  - src: https://github.com/snipem/alfred-dazn
    branch: master
    docdir: .
    targetdir: docs/alfred-dazn

  - src: https://github.com/snipem/alfred-deezer
    branch: master
    docdir: .
    targetdir: docs/alfred-deezer