
name: Build Page with Monako

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Monako
      run: |
        wget -qO- https://github.com/snipem/monako/releases/download/v0.0.12/monako_0.0.12_linux_amd64.tar.gz |
        bsdtar -xvf- -C &&
        chmod +x monako

    - name: Run Monako
      run: ./monako

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: compose/public
